<?php
/**
 * WagesTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  WorkBC\SSoT
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PostgREST API
 *
 * standard public schema
 *
 * The version of the OpenAPI document: 9.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace WorkBC\SSoT\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WagesTest Class Doc Comment
 *
 * @category    Class
 * @description Wages
 * @package     WorkBC\SSoT
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WagesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Wages"
     */
    public function testWages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "noc"
     */
    public function testPropertyNoc()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "occupation_title"
     */
    public function testPropertyOccupationTitle()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "esdc_wage_rate_low_2021"
     */
    public function testPropertyEsdcWageRateLow2021()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "esdc_wage_rate_median_2021"
     */
    public function testPropertyEsdcWageRateMedian2021()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "esdc_wage_rate_high_2021"
     */
    public function testPropertyEsdcWageRateHigh2021()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "calculated_median_annual_salary_2021"
     */
    public function testPropertyCalculatedMedianAnnualSalary2021()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "source_information"
     */
    public function testPropertySourceInformation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
