<?php
/**
 * WagesApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  WorkBC\SSoT
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PostgREST API
 *
 * standard public schema
 *
 * The version of the OpenAPI document: 9.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace WorkBC\SSoT\Test\Api;

use \WorkBC\SSoT\Configuration;
use \WorkBC\SSoT\ApiException;
use \WorkBC\SSoT\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  WorkBC\SSoT
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WagesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for wagesDelete
     *
     * .
     *
     */
    public function testWagesDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wagesGet
     *
     * .
     *
     */
    public function testWagesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wagesPatch
     *
     * .
     *
     */
    public function testWagesPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wagesPost
     *
     * .
     *
     */
    public function testWagesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
